# Generated by Django 6.1.1 on 2026-09-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctorprofile_clinic_doctorprofile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
