# Generated by Django 6.1.1 on 2026-09-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='registration_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
