# Generated by Django 6.1.1 on 2026-09-13 13:23

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_phone_verified_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_id',
            field=models.CharField(default='TEMP001', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', unique=True),
        ),
    ]
