# Generated by Django 6.1.1 on 2026-09-13 16:23

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_doctorprofile_profile_id_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', unique=True),
        ),
    ]
