# Generated by Django 6.1.1 on 2026-09-14 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_doctorprofile_phone_number'),
        ('organizations', '0003_alter_clinic_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='organizations.clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Clinic_Admin_pofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
