# Generated by Django 6.1.1 on 2026-09-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clinicadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClinicAdmin',
        ),
    ]
