# Generated by Django 6.1.1 on 2026-09-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_username'),
        ('doctors', '0003_specialisations'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.specialisations'),
        ),
    ]
