# Generated by Django 6.1.1 on 2026-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='doctors_spe_title_235d9e_idx')],
            },
        ),
    ]
