# Generated by Django 6.1.1 on 2026-09-12 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appoinments', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='doctor_clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='doctors.doctor_clinics'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appoinments.timeslot'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['doctor', 'day_of_week', 'is_active'], name='appoinments_doctor__1caae6_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('appointment_date__lt', models.F('created_at__date'))), name='appointment_date_in_future'),
        ),
    ]
