# Generated by Django 6.1.1 on 2026-09-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_username'),
        ('appoinments', '0003_consultationsession_and_more'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsession',
            name='time_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='appoinments.timeslot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='max_tokens',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exception_type', models.CharField(choices=[('UNAVAILABLE', 'Unavailable'), ('CUSTOM_HOURS', 'Custom Hours')], max_length=30)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='accounts.doctorprofile')),
                ('doctor_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor_clinics')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='appoinments.consultationsession')),
            ],
        ),
    ]
