# Generated by Django 6.1.1 on 2026-09-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_clinic_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='city',
            field=models.CharField(max_length=250),
        ),
    ]
