# Generated by Django 6.1.1 on 2026-09-14 02:36

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_clinic_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clincs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='clinic/banners'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='calling_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='clinic/profile_images'),
        ),
    ]
