# Generated by Django 6.1.1 on 2026-09-14 02:40

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_clinic_admin_clinic_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='calling_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
