# Generated by Django 6.1.1 on 2026-09-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_clinic_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='location',
            new_name='location_url',
        ),
    ]
